### ISSUE TITLE
[feature] Upgrade @web3modal/core-react-native to valtio 1.11.2

### ISSUE THREAD

**Issue by thiagobrez** [WalletConnect/web3modal-react-native#114]
### What problem does this new feature solve?

Would be good to have standard versions of `valtio` across the web and native packages, to avoid https://github.com/WalletConnect/web3modal-react-native/issues/79 happening when installing both web and native SDKs for a cross-platform setup

![Screenshot 2023-12-18 at 13 38 43](https://github.com/WalletConnect/web3modal-react-native/assets/26878038/7a9e84b5-2616-412d-82d4-d98c17095cfa)

### Describe the solution you'd like

Yes, pinning a version with `resolutions` field in `package.json` works, but preferably we wouldn't need to do that when installing both SDKs from Web3Modal

Bump `valtio` in `@web3modal/core-react-native` to `1.11.2`, to match version in other Web3Modal packages

**Comment by ignaciosantise** [comment]
Hi @thiagobrez 👋 last time i tried to upgrade valtio to `1.11.2` it had an [issue](https://github.com/WalletConnect/modal-react-native/issues/96) with Hermes. 

Here is more context in Valtio's repo -> https://github.com/pmndrs/valtio/issues/765

Did you have this error while you were using the sdk?

**Comment by thiagobrez** [comment]
Hey @ignaciosantise ! Yeah that makes sense. I got the error when trying to install both the Web3Modal web and react native SDKs on the same project, for a cross-platform approach, such as in https://github.com/callstack/web3-cross-platform-dapp

I solved by adding the `resolutions` field to package, but ideally when the issue with Hermes is solved, I think this should be handled in the SDK

**Comment by ignaciosantise** [comment]
Updated to `valtio 1.11.2` in the latest release (v2.0.1) 🎉
