### ISSUE TITLE
[feature] wagmi, viem v2 support

### ISSUE THREAD

**Issue by judeProground** [WalletConnect/web3modal-react-native#125]
### What problem does this new feature solve?

wagmi, viem v2 support

### Describe the solution you'd like

Hi, as the main repository of web3modal has released alpha, which supports wagmi v2, need some support as well.
I'm concerned about potential issues with the operation of wagmi v1.

Thanks!

**Comment by judeProground** [comment]
Hi, @glitch-txs. Sorry to mention you. 

https://docs.walletconnect.com/web3modal/v2/about
This document indicates that web3modal v2 is deprecated. 
Is there any update regarding support for wagmi v2? 

Thanks

**Comment by glitch-txs** [comment]
Oh that refers to the Web SDK, React Native one is not deprecated :)

**Comment by glitch-txs** [comment]
We will support Wagmi v2 eventually, I think Nacho is currently working on other prios

**Comment by judeProground** [comment]
Oh, I see. That's great news!
Thank you for confirming.

**Comment by judeProground** [comment]
@glitch-txs Is there any update?

**Comment by r-khr** [comment]
I'm interested in contributing to this feature. Any suggestions on the tasks needed to be done to achieve this?

**Comment by ayaamdouni** [comment]
Hello, any updates refarding support for wagmi v2 ?

**Comment by ignaciosantise** [comment]
Hey @r-khr @vrakovs-abc @ayaamdouni @judeProground we released an alpha version for wagmi v2:

`yarn add npm install @web3modal/wagmi-react-native@alpha wagmi viem @tanstack/react-query @walletconnect/react-native-compat`

Here are the alpha docs:
https://alpha-docs.walletconnect.com/web3modal/react-native/about

And also check the new email wallets section 🖖

**Comment by r-khr** [comment]
Awesome! Works for me, thank you @ignaciosantise
