### ISSUE TITLE
[bug]: New architecture support

### ISSUE THREAD

**Issue by patrikduksin** [WalletConnect/web3modal-react-native#137]
### Description

On the first video I turned on new arch and have some strange behavior: 
1. Slide animation begins from the bottom left edge, should be just from the bottom
2. Wallet logos doesn't show. 

FYU: I tried to change rn image to expo-image and logos show as expected. 

https://github.com/WalletConnect/web3modal-react-native/assets/61261093/11cf5322-940b-46fb-98c9-b10f330dc50c

https://github.com/WalletConnect/web3modal-react-native/assets/61261093/95c9d8c4-36b7-4dd5-af0a-6c056fbd9205

### Web3Modal SDK version

@web3modal/wagmi-react-native 1.2.0

### Output of `npx react-native info`

```
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 184.61 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.asdf/installs/nodejs/20.10.0/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.5
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.0.3
    path: /Users/patrikduksin/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Expo Version (if applies)

Expo 50.0.6

### Steps to reproduce

```
npm i
npx expo run:ios
```

### Snack, code example, screenshot, or link to a repository

https://github.com/patrikduksin/rn-wallet-connect-bug.git

**Comment by glitch-txs** [comment]
Do you get any errors on the console?

**Comment by patrikduksin** [comment]
hey @glitch-txs nothing 
<img width="885" alt="image" src="https://github.com/WalletConnect/web3modal-react-native/assets/61261093/9c6190cd-df9c-4355-a3b1-e441d12a3f69">

**Comment by ignaciosantise** [comment]
Hey @patrikduksin 👋 thanks for reporting!

You should be able to connect to wallets without issues, but sadly it seems that RN new architecture has some issues regarding images -> https://github.com/facebook/react-native/issues/33131

And about the modal animation, its also a dependency issue: https://github.com/react-native-modal/react-native-modal/issues/757

In this case, we'll wait to see if they solve the issue, and if they don't, we'll evaluate migrating to another modal lib

**Comment by patrikduksin** [comment]
@ignaciosantise @glitch-txs Hello, as I see you are not planing to support new arch. It's important for us to use it, so can I use web3modal lib with my own UI modal? Maybe you have a documentation about it

**Comment by ignaciosantise** [comment]
@patrikduksin we added a temporary workaround for the image loading issue in `v1.2.1` version until react-native solves the Image component problem

As i said, except from this UI issues, the SDK supports the new architecture and you should be able to connect with wallets.
