### ISSUE TITLE
Send Basic Events to API

### ISSUE THREAD

**Issue by Sam-Newman** [WalletConnect/web3modal-react-native#146]
Implement basic events:
- [ ]   MODAL_LOADED
- [ ] MODAL_OPEN
- [ ]  MODAL_CLOSE
- [ ]  CLICK_ALL_WALLETS
- [ ]  SELECT_WALLET
- [ ] CLICK_NETWORKS
- [ ] OPEN_ACTIVITY_VIEW
- [ ] SWITCH_NETWORK
- [ ] CONNECT_SUCCESS
- [ ] CONNECT_FAILURE
- [ ] DISCONNECT_SUCCESS
- [ ] DISCONNECT_ERROR
- [ ] CLICK_WALLET_HELP
- [ ] CLICK_NETWORK_HELP

**Comment by ignaciosantise** [comment]
Duplicated of https://github.com/WalletConnect/web3modal-react-native/issues/140

**Comment by ignaciosantise** [comment]
Duplicated of https://github.com/WalletConnect/web3modal-react-native/issues/140
