### ISSUE TITLE
[bug]: Transaction process fails while staying in the wallet app

### ISSUE THREAD

**Issue by itsnyx** [WalletConnect/web3modal-react-native#151]
### Description

Hello, I have problem on confirming transaction on the wallet. 

here is my code: 
```
   const config = await prepareWriteContract({
        address: coin.contract,
        abi: tokenABI,
        functionName: 'transfer',
        args: [
          factor.destination_wallet,
          parseEther(selectedCoin?.value).toString(),
        ],
      });
      const {hash} = await writeContract(config, {});
      await waitForTransaction({
        confirmations: 2,
        hash: hash,
      });
      /// ------ this below line is not executing while user waits for the full confirmation on the wallet app (and our app is in 
           background mode and its waiting for confirmation)

    // this below line only executes when user jumps back to the app right after pressing confirm button.

     // custom function to save data in server database
      await sumbmitTransaction(hash, factor);
```

And my other problem is that wallet app doesn’t  redirect to my app after confirming transaction, how to achieve this on react-native?

### Web3Modal SDK version

    "@web3modal/wagmi-react-native": "^1.2.0",

### Output of `npx react-native info`

System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1
    Memory: 86.28 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /opt/homebrew/opt/node@18/bin/npm
    Watchman: 2023.11.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11330709
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Expo Version (if applies)

    "expo": "^48.0.0"

### Steps to reproduce

confirm a transaction on the wallet app but don’t redirect to the react-native app, in the react-native side the code lines after       const {hash} = await writeContract(config, {});
doesn’t run 

### Snack, code example, screenshot, or link to a repository

```
   const config = await prepareWriteContract({
        address: coin.contract,
        abi: tokenABI,
        functionName: 'transfer',
        args: [
          factor.destination_wallet,
          parseEther(selectedCoin?.value).toString(),
        ],
      });
      const {hash} = await writeContract(config, {});
      await waitForTransaction({
        confirmations: 2,
        hash: hash,
      });
      /// ------ this below line is not executing while user waits for the full confirmation on the wallet app (and our app is in 
           background mode and its waiting for confirmation)

    // this below line only executes when user jumps back to the app right after pressing confirm button.

     // custom function to save data in server database
      await sumbmitTransaction(hash, factor);
```

**Comment by ignaciosantise** [comment]
Hi @itsnyx 👋 regarding the redirect issue:  Apple removed the API that wallets used to "go back" to the previous app and that's why it's not working anymore. Wallets could navigate back to the dapp by reading the deeplink inside the session request metadata. (shouild be in `request.peer.metadata.redirect.native`)

Regarding the issue with wagmi, can you explain a little bit what's the issue?
Is the code blocked in `await waitForTransaction`? Does `await sumbmitTransaction` executes?

**Comment by itsnyx** [comment]
HI, @ignaciosantise  after testing it multiple times only answer i got was : bad internet connection made it so that functions returned error.

and about redirecting back to the dapp there is no way to actually achieve this right now, correct?

**Comment by ignaciosantise** [comment]
@itsnyx About the redirection issue, unfortunately we cannot do anything on our side now. But we are planning to reach wallets to help em implement the redirection correctly.

About the other issue, i'll try to check it but it seems more like an issue from wagmi, did you check if there's any related issue in their repo?

**Comment by itsnyx** [comment]
@ignaciosantise  thanks for the response.
i didn't find anything related about this issue.
 
 ==> I will close this issue now and if i encounter this error again i will open another issue with more detail and with example repo.

**Comment by DanilKasianenko** [comment]
> Hi @itsnyx 👋 regarding the redirect issue: Apple removed the API that wallets used to "go back" to the previous app and that's why it's not working anymore. Wallets could navigate back to the dapp by reading the deeplink inside the session request metadata. (shouild be in `request.peer.metadata.redirect.native`)
> 
> Regarding the issue with wagmi, can you explain a little bit what's the issue? Is the code blocked in `await waitForTransaction`? Does `await sumbmitTransaction` executes?

:(
