### ISSUE TITLE
[bug] React Native - The app cannot select a network and fails to remember account details upon reopening.

### ISSUE THREAD

**Issue by tomheo11233aA** [WalletConnect/web3modal-react-native#156]
### Link to minimal reproducible example
https://github.com/tomheo11233aA/Web3SampleApp.git

### 1. When connect wallet successfully I using select network tab and have a 
**Console Warning:**  Possible unhandled promise rejection: SwitchChainError: An error occurred when attempting to switch chain. 

### 2. When reopen app ( destroy app and open again )

- Show connect button again.
- When press connect button and choose wallet want to connect it's show
**Connection dclined. Connection can be declined if a previous request is still active**

<img height="800" src="https://github.com/WalletConnect/web3modal/assets/127393321/92d6a822-56c3-4f7c-bb26-e387c790a7dc" />

<img height="800" src="https://github.com/WalletConnect/web3modal/assets/127393321/0d1f8dd0-511c-49e1-bb87-5aaad3fe38ee" />

### List of related npm package versions

```jsx
"web3": "^4.7.0"
"wagmi": "^1.4.13"
"viem": "^1.21.4"
"@web3modal/coinbase-wagmi-react-native": "^1.3.0"
"@web3modal/wagmi-react-native": "^1.3.0"
"react-native": "0.73.6"
"@react-native-async-storage/async-storage": "^1.23.1"
```

**Comment by ignaciosantise** [comment]
Hey @tomheo11233aA 👋 thanks for reporting. 

Can you provide steps to reproduce the issue? Also:
* Does it happen with all wallets? Or just with Trust?
* Which version of Trust are you using?
* Can you provide a video with the complete flow?

**Comment by tomheo11233aA** [comment]
Hello @ignaciosantise, thank you for your support.

- I'm unsure. The Metamask app is experiencing issues, preventing me from testing this wallet.
- The latest version on CHPlay is 8.12.2, released on September 4th, 2024.
- The following operations are causing the application to malfunction.
https://github.com/WalletConnect/web3modal-react-native/assets/127393321/c161bb94-99fa-4bd1-bfb7-4e06cec228e2

**Comment by tomheo11233aA** [comment]
@ignaciosantise Hello. I believe this bug has been fixed. Thank you for your support.

**Comment by ignaciosantise** [comment]
@tomheo11233aA great! Did you change anything on your side to fix it? If so, can you write it here so future devs can read it

**Comment by tomheo11233aA** [comment]
@ignaciosantise I didn't reinstall the library or make any changes; I simply ran the app again, and unexpectedly, there were no problems.

**Comment by socheatleang** [comment]
Hello @ignaciosantise  @tomheo11233aA  . Actually. It's the problem. I am using react-native expo which integrate the latest version of **"@web3modal/wagmi-react-native": "^1.3.0"**. 
The step to reproduce. 
1. Connect with one wallet (metamask, trust, etc...)
2. Terminate the app
3. Disconnect with connected wallet 
4. Try to connect the wallet again 
Then the error would say that it's **still active** which lead my user can't connect to the wallet.

To temporary solved this issue, I would need to code AsyncStorage.clear();
