### ISSUE TITLE
[bug]: On android crash when user press on All Wallets

### ISSUE THREAD

**Issue by socheatleang** [WalletConnect/web3modal-react-native#160]
### Description

I am using expo, and everything work smoothly except Pressing the **All Wallets** on android. I got error from native code (see the screenshot).

### Web3Modal SDK version

"@web3modal/wagmi-react-native": "^1.3.0"

### Output of `npx react-native info`

```
System:
    OS: macOS 14.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 28.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2023.2 AI-232.10227.8.2321.11479570
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.14 => 0.71.14 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Expo Version (if applies)

"expo": "~48.0.21",

### Steps to reproduce

I just trigger the open() from useWeb3Modal;

`const { open, close } = useWeb3Modal();` 

With the physical device (dev-client), The modal opened, then I pressed on **All Wallets** , the app got crash

### Snack, code example, screenshot, or link to a repository

![photo_2024-05-15_11-23-41](https://github.com/WalletConnect/web3modal-react-native/assets/98952747/49bcf437-07fa-4764-8370-2cb9b49d4214)

**Comment by socheatleang** [comment]
Hello @ignaciosantise  ;

Do you have any thought about this? I've tried different version. It's still the same

**Comment by ignaciosantise** [comment]
Apparently the error comes from react-native-svg. Which version are you using?

**Comment by socheatleang** [comment]
@ignaciosantise . Thanks. I managed to solved the issue which installs the react-native-svg@1.4.0 ✅

Installing react-native-svg below 1.4.0 will produce the app crash on Android.
