### ISSUE TITLE
[bug] IOS Wallet connect on IOS not working without error.

### ISSUE THREAD

**Issue by Sl00x** [WalletConnect/web3modal-react-native#161]
### Link to minimal reproducible example

Create project on expo sdk 51, config you web3modal wagmi projet. launch commande 'npx expo start' scan qr code on your iPhone try to connect you wallet after wait redirect on expo app and see you're not connected.

### Summary

I've create project using EXPO SDK 51.0.6 with Expo-router, and install web3modal + wagmi from walletconnect documentation.
I have follow all stpe to configure web3modal.
When i press button connect wallet. Wallets modal is shown, when I press on wallet it redirect myself on my wallet's app.
And on my wallet app's when I'm pressing connect it's redirect me to my developpement app using expo-go (phisycal device ios 17.4.5)
And to finish i'm not connect the connect wallet stay here.

### List of related npm package versions

@walletconnect/react-native-compat : 2.10.5
@web3modal/wagmi-react-native : ^1.3.0
ethers: ^6.12.1
view: 1.21.4
wagmi: 1.4.13

**Comment by ignaciosantise** [comment]
Hey @Sl00x 👋 does it happen on Android too? Does it work for other wallets like Trust, Rainbow?

**Comment by Sl00x** [comment]
> Hey @Sl00x 👋 does it happen on Android too? Does it work for other wallets like Trust, Rainbow? Also, can you provide a repository so i can reproduce the issue?

Hey @ignaciosantise it's working fine on android

**Comment by ignaciosantise** [comment]
can you provide a repository so i can reproduce the issue?

**Comment by Sl00x** [comment]
> can you provide a repository so i can reproduce the issue?

I have this issue with this tutorial repo from doc of walletconnect:
https://github.com/crypblizz8/youtube/tree/main/7-web3modal-react-native-nft

**Comment by ignaciosantise** [comment]
@Sl00x i was able to connect using Trust and our react native sample wallet. Can you try connecting to mainnet instead of goerli? In case your wallet doesn't support goerli.

**Comment by ignaciosantise** [comment]
@Sl00x any new?

**Comment by ignaciosantise** [comment]
Closing for now. Reach again if the issue appears again
