### ISSUE TITLE
feat: add metamask wallet

### ISSUE THREAD

**Issue by g-areth** [WalletConnect/web3modal-react-native#18]
Metamask is missing from web 3 modal, but I see it available in `https://explorer-api.walletconnect.com/w3m/v1/getMobileListings`

**Comment by ignaciosantise** [comment]
hey @g-areth, this SDK supports v2 only, and Metamask is still on v1.

Here's an issue with their migration status https://github.com/MetaMask/metamask-mobile/issues/3957#issuecomment-1535544915 + would be great to upvote it!
