### ISSUE TITLE
[bug]: Cannot convert undefined value to object

### ISSUE THREAD

**Issue by GaryJC** [WalletConnect/web3modal-react-native#194]
### Description

When I tried to import WalletConnect to my exisiting RN project, it reported this error when I implement `<Web3Modal/>` in my code. I thought it conflicted with my other installed libraries or frameworks, but when I created a new expo project and installed WalletConnect, I got the same error. I've tried expo 49 ~ 51, but none of versions work.
<img width="408" alt="Screenshot 2024-07-24 at 1 48 33 PM" src="https://github.com/user-attachments/assets/46bc7947-3ec2-4c0f-9231-4c00aa9a3fe5">

### AppKit SDK version

"@web3modal/ethers-react-native": "^2.0.0",

### Output of `npx react-native info`

 OS: macOS 14.5
  CPU: (10) arm64 Apple M2 Pro
  Memory: 370.58 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman:
    version: 2023.08.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /opt/homebrew/opt/openjdk@11/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Expo Version (if applies)

50.0.0

### Steps to reproduce

expo init my-new-project
--blank
cd my-new-project
npx expo install @web3modal/ethers-react-native ethers
npx expo install @react-native-async-storage/async-storage react-native-get-random-values react-native-svg react-native-modal @react-native-community/netinfo @walletconnect/react-native-compat expo-application

App.js:
import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View } from "react-native";

import "@walletconnect/react-native-compat";

import {
  createWeb3Modal,
  defaultConfig,
  Web3Modal,
} from "@web3modal/ethers-react-native";

// 1. Get projectId from https://cloud.walletconnect.com
const projectId = "--------------";

// 2. Create config
const metadata = {
  name: "AppKit RN",
  description: "AppKit RN Example",
  url: "https://walletconnect.com",
  icons: ["https://avatars.githubusercontent.com/u/37784886"],
  redirect: {
    native: "YOUR_APP_SCHEME://",
  },
};

const config = defaultConfig({ metadata });

// 3. Define your chains
const mainnet = {
  chainId: 1,
  name: "Ethereum",
  currency: "ETH",
  explorerUrl: "https://etherscan.io",
  rpcUrl: "https://cloudflare-eth.com",
};

const polygon = {
  chainId: 137,
  name: "Polygon",
  currency: "MATIC",
  explorerUrl: "https://polygonscan.com",
  rpcUrl: "https://polygon-rpc.com",
};

const chains = [mainnet, polygon];

// 4. Create modal
createWeb3Modal({
  projectId,
  chains,
  config,
  enableAnalytics: true, // Optional - defaults to your Cloud configuration
});

export default function App() {
  return (
    <View style={styles.container}>
      <Web3Modal />
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

### Snack, code example, screenshot, or link to a repository

**package.json:**
{
  "name": "my-new-project_2",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/netinfo": "11.1.0",
    "@walletconnect/ethereum-provider": "^2.14.0",
    "@walletconnect/react-native-compat": "^2.14.0",
    "@web3modal/ethers-react-native": "^2.0.0",
    "ethers": "^6.13.1",
    "expo": "^50.0.0",
    "expo-application": "~5.8.4",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-get-random-values": "~1.8.0",
    "react-native-modal": "^13.0.1",
    "react-native-svg": "14.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

**Comment by ignaciosantise** [comment]
Hey @GaryJC 👋  thanks for reporting. I'll look into it

**Comment by ignaciosantise** [comment]
It's a conflict between `valtio` versions. Can you add `"valtio": "1.10.5"` as a dependency in your package.json and install the deps again?

**Comment by GaryJC** [comment]
Hey @ignaciosantise, thanks for replaying. It actually worked! 
I've found a way to solve it either:
must installing` npx expo install @walletconnect/modal-react-native` first
then installing` npx expo install @web3modal/ethers-react-native ethers`, and `npx expo install @react-native-async-storage/async-storage react-native-get-random-values react-native-svg react-native-modal @react-native-community/netinfo @walletconnect/react-native-compat expo-application`.
The key point is installing the `@walletconnect/modal-react-native` before installing other relevant packages. I don't know why the order is important but it worked.
Anyway, your answer is definitely more simple and straightforward. Thanks again!

**Comment by GaryJC** [comment]
Hey @ignaciosantise, thanks for replaying. It actually worked! 
I've found a way to solve it either:
must installing` npx expo install @walletconnect/modal-react-native` first
then installing` npx expo install @web3modal/ethers-react-native ethers`, and `npx expo install @react-native-async-storage/async-storage react-native-get-random-values react-native-svg react-native-modal @react-native-community/netinfo @walletconnect/react-native-compat expo-application`.
The key point is installing the `@walletconnect/modal-react-native` before installing other relevant packages. I don't know why the order is important but it worked.
Anyway, your answer is definitely more simple and straightforward. Thanks again!

**Comment by ignaciosantise** [comment]
Great 🤝 I'll release a new version soon that bumps valtio to `1.11.2` to avoid conflict with versions.
