### ISSUE TITLE
Rainbow | Redirections issue

### ISSUE THREAD

**Issue by boulinb** [WalletConnect/web3modal-react-native#31]
Hi !

Here are the problems I have with the implementation of Rainbow:

When the user logs in via Rainbow, I feel that the redirection is quite random.

Sometimes the user clicks on "Login" and the redirection to the original application is fine, sometimes the user is not redirected.

I don't know if the problem is with Rainbow or the package, but I'd rather open this issue so that you know what the problem is! :)

Here is a working implementation for you to test: https://github.com/boulinb/web3modal-react-native-issue

Thanks to you for your work on the package!

Benjamin

**Comment by StevenBarnett1** [comment]
Same ^^

**Comment by roger-pan** [comment]
+1 We are noticing the same — we'd appreciate it if you could prioritise fixing this 🙏

**Comment by ignaciosantise** [comment]
hey @boulinb @StevenBarnett1 @roger-pan redirection issues are on the wallet side. We already talked with every wallet's team to raise the issue, and it's just a matter of time until they solve it 💪 If you have time, please reach them too so they can prioritize the fix.

**Comment by boulinb** [comment]
Hello everyone !

Redirects now work perfectly well on my side with Rainbow (Tested on iOS) 😄

**Comment by ignaciosantise** [comment]
It also works good on Android v1.8(174) 🎉 

thanks for testing @boulinb
