### ISSUE TITLE
Dependency conflict when project have old version of @walletconnect/core

### ISSUE THREAD

**Issue by m1heng** [WalletConnect/web3modal-react-native#37]
Hi, My project is using walletconnect v1 with `"@walletconnect/react-native-dapp": "1.8.0"` which leads to a dependency of  `"@walletconnect/core": "^1.8.0"`

So when I installed `"@web3modal/react-native": "1.0.0-alpha.4"` and tried to run with it, js error occurred as in `src/hooks/useConfigure.ts`, `SUBSCRIBER_EVENTS` is not defined. Because in `@web3modal/react-native`, it was using `"@walletconnect/core": "^1.8.0"` instead of "@walletconnect/core": "^2"

```
import { SUBSCRIBER_EVENTS } from '@walletconnect/core';
```

fix PR as below

**Comment by ignaciosantise** [comment]
@m1heng good catch! thanks for the PR 🚀 

Apart from this issue, how was the migration process from `@walletconnect/react-native-dapp` to `@web3modal/react-native`? Did you encounter any other issue/blocker?
