### ISSUE TITLE
No matching key. pairing: undefined

### ISSUE THREAD

**Issue by Sotatek-Namdo2** [WalletConnect/web3modal-react-native#38]
I have tried to connect my wallet on the android simulator and got the error:

 ERROR  {"context": "core"} {"context": "core/pairing"} {"context": "core/pairing/pairing"} No matching key. pairing: undefined
 ERROR  {"context": "client"} [Error: No matching key. pairing: undefined]

My current version: 1.0.0-alpha.5
if i use 1.0.0-alpha.3 version there are no errors

**Comment by finessevanes** [comment]
Thanks for reporting - sending to our team!

**Comment by ignaciosantise** [comment]
@Sotatek-Namdo2 this error doesn't block the sdk functionalities, were you able to connect to a wallet?

**Comment by Sotatek-Namdo2** [comment]
> @Sotatek-Namdo2 this error doesn't block the sdk functionalities, were you able to connect to a wallet?
yes. I am still able to connect to wallets

**Comment by dingcxx** [comment]
I was in the same situation, in this situation ModalCtrl.state.open return false, then call ModalCtrl.open status is well

**Comment by ignaciosantise** [comment]
hey @dingcxx 👋 can you open a new issue with your situation? As it's not related with the one described here

**Comment by arbaz-meo** [comment]
@finessevanes  @ignaciosantise  today i also encounter this issue  with signclient (2.7.7) before its not was present . 

`{"level":50,"time":1686049828249,"pid":2012656,"hostname":"mywhooshsupport01","context":"core","context":"core/pairing","context":"core/pairing/pairing","msg":"No matching key. pairing: undefined"}`

**Comment by ignaciosantise** [comment]
@Sotatek-Namdo2 @dingcxx @arbaz-meo This error is solved in the latest version of https://github.com/WalletConnect/modal-react-native

Please migrate to the new lib 💪
