### ISSUE TITLE
[bug] Can't find variable: React

### ISSUE THREAD

**Issue by therealharpaljadeja** [WalletConnect/web3modal-react-native#58]
### Link to minimal reproducible example

Just using the package in react-native screens

### Summary

I get this error from web3modal package

<img width="1107" alt="image" src="https://github.com/WalletConnect/web3modal/assets/38040789/9e1858db-4e30-4a67-8306-7502fa436d49">

### List of related npm package versions

react-native - 0.69.5
@web3modal/react-native: ^1.0.0-alpha.5

**Comment by ignaciosantise** [comment]
hey @therealharpaljadeja 👋 Adding `"jsx": "react-jsx"` in your `tsconfig.json` file should work.

```js
// tsconfig.json
{
  "compilerOptions": {
    ...
    "jsx": "react-jsx"
    ...
  },
}
```

More info [here](https://stackoverflow.com/a/65539274/6562073)

**Comment by therealharpaljadeja** [comment]
Tried didn't work 😅

<img width="434" alt="image" src="https://github.com/WalletConnect/web3modal-react-native/assets/38040789/009bb696-f3fd-4757-893b-9b6db79348ee">

<img width="620" alt="image" src="https://github.com/WalletConnect/web3modal-react-native/assets/38040789/f8076f1f-519a-4de6-a9ae-dd025dfcd4f2">

**Comment by therealharpaljadeja** [comment]
This solved it!

https://github.com/facebook/react-native/issues/34351
