### ISSUE TITLE
[bug]: Trust wallet - No matching key. pairing: undefined

### ISSUE THREAD

**Issue by StevenBarnett1** [WalletConnect/web3modal-react-native#60]
### Description

When connecting on trust wallet on polygon im getting these errors 
 
 ERROR  {"context": "core"} {"context": "core/pairing"} {"context": "core/pairing/pairing"} No matching key. pairing: undefined
 ERROR  {"context": "client"} [Error: No matching key. pairing: undefined]

Then when trying to send a transaction it says walletconnect session disconnected and i see this error:

 ERROR  {"context": "core"} {"context": "core/expirer"} No matching key. expirer: topic:f3049d397e51dfeeabb06bc2f843cf733a667679fb20923f7ed56b1cfec8a9f7

### Web3Modal SDK version

1.0.0-alpha.7

### Output of `npx react-native info`

 ERROR  {"context": "core"} {"context": "core/pairing"} {"context": "core/pairing/pairing"} No matching key. pairing: undefined
 ERROR  {"context": "client"} [Error: No matching key. pairing: undefined]

 ERROR  {"context": "core"} {"context": "core/expirer"} No matching key. expirer: topic:f3049d397e51dfeeabb06bc2f843cf733a667679fb20923f7ed56b1cfec8a9f7

### Steps to reproduce

Try to connect to alphawallet on polygon and see the first error. Then try to send a transaction and i get the second error and trustwallet says walletconnect is disconnected

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2023-06-16 at 10 59 36 AM](https://github.com/WalletConnect/web3modal-react-native/assets/73503506/0c6b65dc-3145-46b2-9945-33a38abb64ab)

**Comment by StevenBarnett1** [comment]
Update: It looks like this only happens if i add an object to rpcMap, if i leave it as an empty object it works. How can i use a custom rpc endpoint to avoid congestion if this doesnt work? The transaction still doesn't go through because of the failed to decrypt error from trustwallet though.

**Comment by ignaciosantise** [comment]
hey @StevenBarnett1 👋 The `Error: No matching key. pairing: undefined` error is not related with the wallets, and you shouldn't worry about it. It's a log coming from one of our core packages that won't affect functionalities. We'll remove it soon.

Trust Wallet still has this [issue](https://github.com/WalletConnect/web3modal-react-native/issues/22) that doesn't allow web3modal work properly, not even the web sdk using deeplinks. Trust is aware of this, but im not sure when they'll fix it. 

If you still want to test with Trust, the Android version works good

**Comment by StevenBarnett1** [comment]
Thanks for the response, we're only on ios right now. What about the rpcMap issue in my second comment?

**Comment by ignaciosantise** [comment]
Hey @StevenBarnett1 can you explain what works/doesnt work adding a custom rpc endpoint?

**Comment by ignaciosantise** [comment]
Also, Trust Wallet v8.9 is already available for iOS

**Comment by StevenBarnett1** [comment]
When I add custom RPC endpoint and use trustwallet when it opens trustwallet and tries to connect it says that it has been disconnected. This doesn't happen if i have rpcMap as an empty object though. So not a huge deal but it is strange
