### ISSUE TITLE
[bug]: Rainbow wallet connection bug

### ISSUE THREAD

**Issue by StevenBarnett1** [WalletConnect/web3modal-react-native#63]
### Description

See picture: 

![IMG_3993](https://github.com/WalletConnect/web3modal-react-native/assets/73503506/e98641f7-b579-4c5c-abf6-843aae832a3a)

### Web3Modal SDK version

1.0.0-alpha.8

### Output of `npx react-native info`

INFO  Inactive pairings cleared: 4
 INFO  {"context": "core"} {"context": "core/relayer"} {"context": "core/relayer/subscription"} Emitting subscription_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_created
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_expired
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_expired
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_expired
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_expired
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_expired
 INFO  {"context": "core"} {"context": "core/expirer"} Emitting expirer_expired
 INFO  {"context": "core"} {"context": "core/history"} Emitting history_updated

### Steps to reproduce

Try initiating a connection with rainbow wallet

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by ignaciosantise** [comment]
Hey @StevenBarnett1 can you check you are using the latest version of Rainbow + send your session params? 

One possible reason of the error is that Rainbow doesn't support `eth_signTransaction`, so if you are sending it in your session params, can you try removing it?

**Comment by StevenBarnett1** [comment]
That was the problem! Thanks
