### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by taibenvenuti** [WalletConnect/web3modal-react-native#7]
After following the expo installation [instructions](https://docs.walletconnect.com/2.0/reactnative/web3modal/installation) in the docs and pressing the Connect button, the modal appears for a fraction of a second and then I get error message:

 ERROR  {"context": "client"} undefined is not a function
 
 And this pops up:
 
 ![error](https://i.imgur.com/P1R3QnL.png)
 
 I reported this issue in the discord channel, and was asked to open an issue about it. Please let me know if there is any other information you need from me and I'll be happy to provide it.

**Comment by ignaciosantise** [comment]
Hey @taibenvenuti 👋 Can you provide your expo and react-native versions? Also, can you check if adding `expo-crypto` and the shim solves the problem? Steps [here](https://docs.walletconnect.com/2.0/reactnative/web3modal/installation#additional-setup-for-expo-sdk-48)

**Comment by taibenvenuti** [comment]
Expo package version is 48.0.15
Output from `yarn expo --version` is 0.7.1 though.
React Native version is 0.71.7

As for the shim and expo-crypto, i had that already. As mentioned earlier I did follow the installation intructions for expo to the letter :)

**Comment by taibenvenuti** [comment]
Adding these as well in case they can be useful


![Screenshot_20230427_001144_host exp exponent](https://user-images.githubusercontent.com/15929385/234704253-4651e02c-7cb8-4ca2-8fa3-6d5a2845eac3.jpg)
![Screenshot_20230427_001235_host exp exponent](https://user-images.githubusercontent.com/15929385/234704257-614fcaf5-cdd3-4164-bd1e-096af639d17d.jpg)

**Comment by taibenvenuti** [comment]
@ignaciosantise that's interesting to know. I will try again on a brand new project then.
I am using Expo Go app on Android 12 device, but starting the server without the --android flag, otherwise it doesn't work for me.

**Comment by taibenvenuti** [comment]
@ignaciosantise I just started a fresh project, followed the instructions, and it works!!

 I am not really sure what I have on my existing project that prevents it from working but I will now migrate the code to this new project and keep checking along the way. Thanks for the help, and sorry for the time wasted!
 
 If I find out what was the real issue, i'll post on here.

**Comment by ignaciosantise** [comment]
@taibenvenuti good to know it works!
