### ISSUE TITLE
W3mButton & Modal aren't auto-connecting wallet in React-Native

### ISSUE THREAD

**Issue by asapboo** [WalletConnect/web3modal-react-native#78]
**Describe the bug**

**SDK Version (if relevant)**
 - Client: React-Native CLI
 - Viem: 1.16.6
 - WAGMI: 1.4.5
 - React-Native: 0.72.4

**To Reproduce**
1. Create a react native cli app and install the wallet connect dependencies
2. Configure the _app page accordingly
3. Run the app and connect wallet. 
4. Close the app and re-open

**Expected behavior**
If the user has already connected and approved the app, they stay connected until they choose to disconnect. 

**Desktop (please complete the following information):**
 - OS: iOS, Swift 3

**Smartphone (please complete the following information):**
 - Device: iOS 14
 - IOS 17.0.3

**Additional context**
Works as expected on React.

**Comment by ignaciosantise** [comment]
Hey @asapboo 👋 can you share your implementation? The re-connection should work well

**Comment by asapboo** [comment]
Sure thing! I have an _app.tsx, a home screen, & a Tabs component.

Home screen, I show the W3m button for the first time and then in each tab,
show it in the header as well.

Cheers, thanks for the quick reply!
Nishant M

**Comment by ignaciosantise** [comment]
👌  can you provide an example app where i can reproduce the issue?

**Comment by asapboo** [comment]
Yea! check this out, should reproduce the error.
 TMAPP.zip
<https://drive.google.com/file/d/1NzI51CtuQ_WJI6jhcgW3E_PsUZY271nA/view?usp=drive_web>

Cheers,

**Comment by glitch-txs** [comment]
could you share a public repository or a code sandbox instead?

**Comment by asapboo** [comment]
apologies, take a look at this https://github.com/asapboo/TMAPP

**Comment by ignaciosantise** [comment]
hey @asapboo the problem is how you define the chains. As you can see in the docs [here](https://docs.walletconnect.com/web3modal/react-native/about#implementation) the `chain` object is just an array with chains. 

In your code you are doing this to get the chain object:

```
const {chains, publicClient, webSocketPublicClient} = configureChains(
  [mainnet],
  [publicProvider()],
);
```
`configureChains`

**Comment by asapboo** [comment]
Ahh I see, it's working now, thank you!

**Comment by asapboo** [comment]
Actually sorry, unfortunately this did not fix the issue.

When I close and re-open the app, it still forces me to re-connect my
wallet.

**Comment by ignaciosantise** [comment]
@asapboo i found the issue. There's an error in the WalletConnectConnector in how i handle the storage. 
As a workaround until i fix it, you can solve it by adding another chain to the array.

for example:

`const chains = [mainnet, polygon];`

**Comment by asapboo** [comment]
I think I have the same setup currently?

**Comment by ignaciosantise** [comment]
The issue will be solved in the next release 🎉

**Comment by asapboo** [comment]
Sweet looking forward to it - thanks for the help!

**Comment by ignaciosantise** [comment]
@asapboo the issue was solved in `1.0.0-alpha.14`. Thanks for reporting 🎉

**Comment by asapboo** [comment]
Hey! I installed the new version but am running into these 4 new errors -

**Comment by asapboo** [comment]
sample app - https://github.com/asapboo/TMAPP

**Comment by ignaciosantise** [comment]
@asapboo which errors do you see?

**Comment by asapboo** [comment]
Issues:

WARN - Please use proxy object at W3mButton

(vanilla.js) TypeError: Cannot convert undefined value to object (3x)

**Comment by ignaciosantise** [comment]
@asapboo you have some issues in your `yarn.lock` file. Can you delete it, delete `node_modules` folder and install the dependencies again?

`rm yarn.lock && rm -rf node_modules && yarn install`

**Comment by asapboo** [comment]
ah sweet deleting the yarn.lock file did it for me - thanks for the help
and fix!
