### ISSUE TITLE
[bug]: : Cannot convert undefined value to object

### ISSUE THREAD

**Issue by nikitapilgrim** [WalletConnect/web3modal-react-native#79]
### Description

 TypeError: Cannot convert undefined value to object

This error is located at:
    in Web3Modal (created by Web3Provider)
    in QueryClientProvider (created by WagmiConfig)
    in WagmiConfig (created by Web3Provider)
    in Web3Provider (created by Providers)

### Web3Modal SDK version

1.0.0-alpha.13

### Output of `npx react-native info`

System:
  OS: macOS 14.1
  CPU: (8) arm64 Apple M1
  Memory: 792.44 MB / 16.00 GB
  Shell:
    version: 3.6.1
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 18.17.1
    path: ~/.volta/tools/image/node/18.17.1/bin/node
  Yarn:
    version: 4.0.0-rc.48
    path: ~/.volta/tools/image/yarn/4.0.0-rc.48/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.volta/tools/image/node/18.17.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.1
    path: /opt/homebrew/opt/openjdk/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.6
    wanted: ^0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Expo Version (if applies)

49.0.16

### Steps to reproduce

I used the steps from the documentation 

### Snack, code example, screenshot, or link to a repository

https://docs.walletconnect.com/web3modal/react-native/about

**Comment by ignaciosantise** [comment]
Hey @nikitapilgrim 👋  could you share a public repository or a code sandbox with the reproducible issue?

**Comment by nikitapilgrim** [comment]
I see what the problem is. I have already used valtio in my project. How can I solve this problem?

**Comment by nikitapilgrim** [comment]
After removing valtio everything started working, but I need valtio

**Comment by ignaciosantise** [comment]
@nikitapilgrim that's interesting 🤔 So the difference between valtio versions is bringing issues.

As a workaround you can add this in your package.json and install `node_modules` again. `resolutions` forces to install that version only. Our package should work with that version too

```
"resolutions": {
    "valtio":"1.11.2"
  },
```

Let me know if that helps for now

**Comment by nikitapilgrim** [comment]
its work
