### ISSUE TITLE
[bug]: Promise.allSettled and Promise.any is undefined

### ISSUE THREAD

**Issue by nikitapilgrim** [WalletConnect/web3modal-react-native#83]
### Description

seems to be a hermes problem, but I think it's worth mentioning in the documentation 

### Web3Modal SDK version

1.0.0-alpha.13

### Output of `npx react-native info`

System:
OS: macOS 14.1
CPU: (8) arm64 Apple M1
Memory: 792.44 MB / 16.00 GB
Shell:
version: 3.6.1
path: /opt/homebrew/bin/fish
Binaries:
Node:
version: 18.17.1
path: ~/.volta/tools/image/node/18.17.1/bin/node
Yarn:
version: 4.0.0-rc.48
path: ~/.volta/tools/image/yarn/4.0.0-rc.48/bin/yarn
npm:
version: 9.6.7
path: ~/.volta/tools/image/node/18.17.1/bin/npm
Watchman: Not Found
Managers:
CocoaPods:
version: 1.14.2
path: /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms:
- DriverKit 23.0
- iOS 17.0
- macOS 14.0
- tvOS 17.0
- watchOS 10.0
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Xcode:
version: 15.0.1/15A507
path: /usr/bin/xcodebuild
Languages:
Java:
version: 21.0.1
path: /opt/homebrew/opt/openjdk/bin/javac
Ruby:
version: 2.6.10
path: /usr/bin/ruby
npmPackages:
"@react-native-community/cli": Not Found
react:
installed: 18.2.0
wanted: ^18.2.0
react-native:
installed: 0.72.6
wanted: ^0.72.6
react-native-macos: Not Found
npmGlobalPackages:
"react-native": Not Found
Android:
hermesEnabled: true
newArchEnabled: false
iOS:
hermesEnabled: true
newArchEnabled: false

### Expo Version (if applies)

49.0.16

### Steps to reproduce

*

### Snack, code example, screenshot, or link to a repository

*

**Comment by nikitapilgrim** [comment]
this will help you 

`import { polyfillObjectProperty } from 'react-native/Libraries/Utilities/PolyfillFunctions';
function allSettled(promises) {
  let mappedPromises = promises.map(p => {
    return p
      .then(value => {
        return {
          status: 'fulfilled',
          value,
        };
      })
      .catch(reason => {
        return {
          status: 'rejected',
          reason,
        };
      });
  });
  return Promise.all(mappedPromises);
}

polyfillObjectProperty(Promise, 'allSettled', () => allSettled);`

**Comment by ignaciosantise** [comment]
@nikitapilgrim could you share a public repository or a code sandbox with the reproducible issue?

**Comment by nikitapilgrim** [comment]
> @nikitapilgrim could you share a public repository or a code sandbox with the reproducible issue?

https://github.com/WalletConnect/web3modal-react-native/tree/V1/apps/native
have you tried running it with hermes?

**Comment by ignaciosantise** [comment]
@nikitapilgrim hermes is turned on by default in that project, and i didn't have the issue

**Comment by nikitapilgrim** [comment]
I get it, the Sentry library patches the Promise global

**Comment by MSohailMemon** [comment]
@nikitapilgrim if Sentry library is patching then what could be the solution for this?
