### ISSUE TITLE
[bug]: Pressing Cross Icon for closing results error

### ISSUE THREAD

**Issue by itsnyx** [WalletConnect/web3modal-react-native#87]
### Description

Hello have nice day.
when im pressing Cross icon to close the modal :
In Iphone: 
it doesn't work and it becomes un responsive (after pressing cross icon when i click blank area on top of the modal to close the modal that also doesn't work).

in Android : 
It throws error: 
![image](https://github.com/WalletConnect/web3modal-react-native/assets/74738973/b5adbc90-a80a-45b1-81e7-49f4202460ef)
and after this also can't close the modal and modal becomes fully unresponsive.

My project is bare react native project but added expo on it.

### Web3Modal SDK version

1.0.0-alpha.13

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 1.90 GB / 15.86 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31, 33, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 33.0.0, 33.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-223.8836.35.2231.10406996
    Visual Studio: Not Found
  Languages:
    Java: 11.0.18 - C:\Program Files\Microsoft\jdk-11.0.18.10-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Expo Version (if applies)

    "expo": "^48.0.0",

### Steps to reproduce

clone example and try it on android emulator 

### Snack, code example, screenshot, or link to a repository

https://github.com/itsnyx/wc-test-repo-temp

**Comment by ignaciosantise** [comment]
Hey @itsnyx 👋 Can you share a public repository where i can reproduce the issue? I'll help me to find the problem.
We've tested the SDK against expo and RN CLI projects and this didn't happen,

**Comment by itsnyx** [comment]
@ignaciosantise 
i have created a test repository for this, i think problem is with react native 0.71.8 i also tested the example project from react native with react native 0.72.6 that worked with no problem but with mine its not working!

here is the repo : 
https://github.com/itsnyx/wc-test-repo-temp

**Comment by ignaciosantise** [comment]
@itsnyx thanks for the public example 🎉 The problem is that im animating the background color of the buttons to create an effect when pressed, but apparently older RN versions don't support animating the backgroundColor with `useNativeDriver: true`.

I'll dig more on this, but i'll probably have to change this effect.

If this blocks you now, you can set `useNativeDriver: false` in `useAnimatedValue` hook until i fix it

**Comment by itsnyx** [comment]
@ignaciosantise can you please specify which files should i change the useNativeDriver value, because they are several of them inside web3modal package?

thanks

**Comment by ignaciosantise** [comment]
@itsnyx Just as a workaround change all of them

**Comment by ignaciosantise** [comment]
@itsnyx the issue was solved in 1.0.0-alpha.14. Thanks for reporting 🎉

**Comment by itsnyx** [comment]
@ignaciosantise  thanks for the update.
