### ISSUE TITLE
[feature] Getting connected wallet metadata

### ISSUE THREAD

**Issue by itsnyx** [WalletConnect/web3modal-react-native#92]
### What problem does this new feature solve?

I want to get connected wallet info such as icon and name.

this was possible with previously versions via provider.

### Describe the solution you'd like

adding a hook can solve this issue, or maybe there is a solution i don’t t know .

thanks.

**Comment by ignaciosantise** [comment]
Hey @itsnyx 👋 you can access the provider and then the session using the `useAccount` hook:

`const {connector} = useAccount();`

and then

```
const provider = await connector?.getProvider();
console.log(provider.session);
```

**Comment by itsnyx** [comment]
hello @ignaciosantise i've checked the provider and it was ok but somehow there were no icons for Metamask wallet i don't know where is the problem, but other metadata such as name link etc were present and ok.

thanks for the help.
