### ISSUE TITLE
[feature] Support `eth_signTypedData_v4` RPC method

### ISSUE THREAD

**Issue by alanmartinez24** [WalletConnect/web3modal-react-native#98]
### What problem does this new feature solve?

Wagmi's `useSignTypedData` hook invokes `eth_signTypedData_v4` RPC method but it is not supported by WalletConnect.
Thus, wagmi's hook does not work.

### Describe the solution you'd like

By supporting `eth_signTypedData_v4` RPC method in WalletConnect providers, `useSignTypedData` will be working fine.

**Comment by glitch-txs** [comment]
Solved on discord 👍
